### PR TITLE
Update container and packages.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
@samcmill @hcheung01 I don't think we settled on how to bump the NGC container, but this is a fairly significant update and would be a good time to validate again.

**Comment by hcheung01** [comment]
@maleadt I will followup after coordinating with the team to discuss the start date on updating Julia. Thank you!

**Comment by hcheung01** [comment]
@maleadt I will followup after coordinating with the team to discuss the start date on updating Julia. Thank you!

**Comment by hcheung01** [comment]
Hey Tim,

Nice to hear from you. I passed along your question to our team and someone
will get back to you as soon as possible. Hope all is well.

**Pull request merged**
