### PR TITLE
Precompile during container build.

### LINKED ISSUE #4: Precompiling at container build time
It would be highly advantageous to precompile the CUDA packages when building the container image.  

The limitation seems to be that the `CUDAdrv` package requires the real CUDA driver.  It would be nice if it could be built against the CUDA stub library (the real library would be available at runtime).

### PR DESCRIPTION
**Pull request by maleadt**
Experimental branch to try and fix https://github.com/maleadt/julia-ngc/issues/4
@samcmill it would be great if you could give this a go.

### CODE REVIEW

**Comment by samcmill** [comment]
@maleadt After a small fix (below), this works for me.  Of course my spot testing is not as exhaustive as the NGC validation.

I tested the Docker (root), Docker (non-root) and Singularity cases, for each of the included test cases.  Other than the `test_cuarrays.jl` example, which had 2 failures for all the container scenarios, all the examples ran successfully.  I'm assuming these failures are not specifically container related.

```
Test Summary:                    | Pass  Fail  Total
CuArrays                         | 4607     2   4609
  GPUArrays test suite           | 1102     2   1104
    construction                 |  515          515
    parallel execution interface |    7            7
    indexing                     |   84           84
    input/output                 |    5            5
    base functionality           |   28           28
    mapreduce                    |  251     2    253
      Float32                    |   38           38
      Float64                    |   38           38
      Int32                      |   38           38
      Int64                      |   38           38
      Complex{Float32}           |   29     1     30
        mapreducedim             |   18           18
        sum maximum minimum prod |    8            8
        broadcasted arrays       |    3     1      4
      Complex{Float64}           |   29     1     30
        mapreducedim             |   18           18
        sum maximum minimum prod |    8            8
        broadcasted arrays       |    3     1      4
      any all ==                 |   21           21
      isapprox                   |   20           20
...
ERROR: LoadError: Some tests did not pass: 4607 passed, 2 failed, 0 errored, 0 broken.
```

The following change was necessary for Docker (non-root) and Singularity because the permissions on the CUDAdrv, CUDAnative, etc. package directories were too restrictive.

```
--- a/Dockerfile
+++ b/Dockerfile
@@ -26,7 +26,9 @@ RUN JULIA_DEPOT_PATH=/usr/local/share/julia \
     chmod 755 /usr/local/share/julia/packages/*/*/deps/usr && \
     # work around JuliaLang/julia#25971
     # (this will matter when precompiling during container build)
-    chmod 644 /usr/local/share/julia/compiled/*/*/*.ji
+    chmod 644 /usr/local/share/julia/compiled/*/*/*.ji && \
+    # additional work around
+    chmod 755 /usr/local/share/julia/packages/*/*
 
 
 # user environment
```

**Comment by maleadt** [comment]
Great, thanks. I'd rather not do a blanket chmod, so I'll look into what causes the permission mismatch. Can you post what failed?

There shouldn't be any test failures, since these test a Manifest of known-good versions that pass our CI (see the status indicator on this PR). Could you also post what failed?

Either way, it'll take a while before the necessary changes have stabilized and are part of a new package versions, but I at least wanted to put this out here already so you know we're working on this.

**Comment by samcmill** [comment]
Test failure:

```
broadcasted arrays: Test Failed at /usr/local/share/julia/packages/GPUArrays/zblJV/src/testsuite/mapreduce.jl:38
  Expression: compare((x->begin
            mapreduce((z->begin
                        z + one(z)
                    end), +, Broadcast.Broadcasted(+, (x, x)); init=zero(ET))
        end), AT, rand(range, dims))
Stacktrace:
 [1] test_mapreduce(::Type) at /usr/local/share/julia/packages/GPUArrays/zblJV/src/testsuite/mapreduce.jl:38
 [2] test(::Type{CuArray}) at /usr/local/share/julia/packages/GPUArrays/zblJV/src/testsuite.jl:58
 [3] top-level scope at /usr/local/share/julia/packages/CuArrays/ojgjv/test/base.jl:8
 [4] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
 [5] top-level scope at /usr/local/share/julia/packages/CuArrays/ojgjv/test/base.jl:8
```

**Comment by samcmill** [comment]
Also

```
ERROR: LoadError: Package CuArrays errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/Types.jl:112
 [2] #test#119(::Bool, ::Nothing, ::typeof(Pkg.Operations.test), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/Operations.jl:1288
 [3] #test at ./none:0 [inlined]
 [4] #test#62(::Bool, ::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Pkg.API.test), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:245
 [5] test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:233 [inlined]
 [6] #test#61 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:230 [inlined]
 [7] test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:230 [inlined]
 [8] #test#60 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:229 [inlined]
 [9] test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:229 [inlined]
 [10] #test#59(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Pkg.API.test), ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:228
 [11] test(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Pkg/src/API.jl:228
 [12] top-level scope at /workspace/examples/test_cuarrays.jl:3
 [13] include at ./boot.jl:328 [inlined]
 [14] include_relative(::Module, ::String) at ./loading.jl:1094
 [15] include(::Module, ::String) at ./Base.jl:31
 [16] exec_options(::Base.JLOptions) at ./client.jl:295
 [17] _start() at ./client.jl:464
in expression starting at /workspace/examples/test_cuarrays.jl:3
```

**Comment by maleadt** [comment]
Also cc @ali-ramadhan @simonbyrne; IIRC you guys were at one point interested in precompiling CUDA on a login node with no CUDA available. The Manifest in this PR points to package versions of the CUDA stack where this is possible, any feedback (here or at https://github.com/JuliaGPU/CuArrays.jl/pull/466, https://github.com/JuliaGPU/CUDAnative.jl/pull/482 or https://github.com/JuliaGPU/CUDAdrv.jl/pull/169) would be useful.

**Comment by simonbyrne** [comment]
Very cool! Would be interesting to see if we can build a container in CI to deploy.

**Comment by ali-ramadhan** [comment]
That's great! So we can do
```julia
using CUDAnative, CuArrays, CUDAdrv
```
on a computer without a GPU and nothing bad will happen? Right now I use a `@hascuda` macro around that expression, but can try removing it and see if tests pass.

**Comment by simonbyrne** [comment]
@ali-ramadhan I think this will let you precompile (which currently is [not possible](https://discourse.julialang.org/t/cuarrays-cudanative-psa-simplified-package-loading/27897/3?u=simonbyrne)), but I think you would still need
```julia
if CUDAapi.has_cuda()
    using CuArrays
end
```

**Comment by maleadt** [comment]
Exactly; importing the packages will still fail (because `__init__` performs a bunch of checks), but you can `Pkg.precompile` to get rid of the latency of importing the packages. That is to say, there's still a bunch of optimizations possible (reduce time in `__init__`, ship a proper `precompile.jl`, etc), but at least the core (somewhat breaking) changes are here now.

@samcmill It just dawned on me, that mapreduce failure is bad. Which GPU generation was this on? I probably need to extend the scope of the hack from https://github.com/JuliaGPU/CUDAnative.jl/pull/479 -- I also contacted @maxpkatz about this to get some info about the range & cause of this bug.

**Comment by samcmill** [comment]
@maleadt The machine I tested this on and got the mapreduce failure has a Pascal GPU (Quadro GP100 to be precise).

**Comment by maleadt** [comment]
Thanks, can reproduce on a P100. That's disappointing, looks like I'll have to disable that feature for everything below Turing/Volta.

**Comment by maleadt** [comment]
Required changes have been merged and tagged, so we can go ahead and merge this. It should greatly improve usability of the image.

**Pull request merged**
